name: Build FreeRDP DLLs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install MSYS2
        run: |
          choco install msys2 -y
          choco install make -y

      - name: Initialize MSYS2
        run: |
          # Set environment variables for MSYS2
          echo ::set-env name=MSYS2_PATH::C:\tools\msys64
          echo ::add-path::C:\tools\msys64\usr\bin

          # Initialize MSYS2
          C:\tools\msys64\msys2_shell.cmd -no-start -defterm -here -msys

      - name: Install FreeRDP dependencies
        run: |
          pacman -Sy --noconfirm mingw-w64-x86_64-pkg-config mingw-w64-x86_64-cmake mingw-w64-x86_64-gcc

      - name: Build FreeRDP
        run: |
          mkdir build
          cd build
          cmake -G "MSYS Makefiles" ..
          make

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: FreeRDP DLLs for Windows x64
          path: build/
