name: Build FreeRDP for Windows x64

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSVC 2012
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Packages
        run: choco install cmake ninja openssl ffmpeg nasm strawberryperl --ignore-reboot

      - name: Install Zlib
        uses: madler/zlib
  
      - name: Set Environment Variables
        run: echo "PKG_CONFIG_PATH=C:/ProgramData/chocolatey/lib/ffmpeg/tools/ffmpeg/share/pkgconfig" >> $GITHUB_ENV
  
      - name: Create Build Directory
        run: mkdir ${{ github.workspace }}/build
  
      - name: Build FreeRDP
        run: |
          cd ${{ github.workspace }}
          cmake .
          cmake --build build --target install
  
      - name: Archive Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build_artifacts
          path: ${{ github.workspace }}/install/