name: Build FreeRDP
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSVC
        uses: microsoft/setup-msbuild@v1

      - name: Install OpenSSL
        run: |
          curl -LO https://slproweb.com/download/Win64OpenSSL-1_1_1k.exe
          Start-Process -Wait -FilePath .\Win64OpenSSL-1_1_1k.exe -ArgumentList "/silent /verysilent /sp- /suppressmsgboxes /DIR=C:\OpenSSL"
          Remove-Item -Force .\Win64OpenSSL-1_1_1k.exe

      - name: Install CMake
        run: |
          curl -LO https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3-win64-x64.zip
          Expand-Archive -Path .\cmake-3.21.3-win64-x64.zip -DestinationPath C:\CMake
          Remove-Item -Force .\cmake-3.21.3-win64-x64.zip

      - name: Build FreeRDP
        run: |
          cd FreeRDP
          mkdir build
          cd build
          cmake ..
          cmake --build . --config Release

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: FreeRDP DLLs
          path: FreeRDP/build/bin
