name: Build FreeRDP on Windows

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Packages
      run: |
        choco install cmake openssl git
        choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

    - name: Clone FreeRDP Source
      run: git clone https://github.com/FreeRDP/FreeRDP.git

    - name: Build FreeRDP
      run: |
        cd FreeRDP
        cmake -DBUILD_SHARED_LIBS=OFF -DOPENSSL_ROOT_DIR=C:/ProgramData/chocolatey/lib/openssl/local/ssl -G"Visual Studio 16 2019" -A x64 .
        cmake --build . --config Release

    - name: Archive Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build_artifacts
        path: FreeRDP/
