name: Build FreeRDP

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSVC
        uses: microsoft/setup-msvc@v1.0.2

      - name: Install OpenSSL
        run: |
          curl -LO https://slproweb.com/download/Win64OpenSSL_Light-1_1_1l.exe
          Start-Process -Wait -FilePath .\Win64OpenSSL_Light-1_1_1l.exe -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES /DIR=C:\OpenSSL"
          Remove-Item .\Win64OpenSSL_Light-1_1_1l.exe

      - name: Install CMake
        run: |
          curl -LO https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3-windows-x86_64.zip
          Expand-Archive -Path .\cmake-3.21.3-windows-x86_64.zip -DestinationPath C:\CMake
          Remove-Item .\cmake-3.21.3-windows-x86_64.zip

      - name: Build FreeRDP
        run: |
          cd FreeRDP
          cmake -B build .
          cmake --build build --config Release

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: FreeRDP DLLs
          path: FreeRDP/build
