name: Build FreeRDP DLLs
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          architecture: x64

      - name: Install OpenSSL
        run: |
          curl -L -o openssl.exe https://slproweb.com/download/Win64OpenSSL-1_1_1L.exe
          Start-Process -Wait -NoNewWindow -FilePath openssl.exe -ArgumentList "/silent /sp- /suppressmsgboxes /DIR=C:\OpenSSL-Win64"
          Remove-Item openssl.exe

      - name: Install CMake
        run: |
          curl -L -o cmake.msi https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3-windows-x86_64.msi
          Start-Process -Wait -NoNewWindow -FilePath msiexec.exe -ArgumentList "/i cmake.msi /quiet"
          Remove-Item cmake.msi

      - name: Build FreeRDP
        run: |
            cd ${{ github.workspace }}
            cmake -DCHANNEL_URBDRC=OFF -DWITH_DSP_FFMPEG=ON -DBUILD_SHARED_LIBS=OFF -Bbuild -S .
            cmake --build build --target install
        

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: FreeRDP-Artifact
          path: FreeRDP/Release
