name: Build FreeRDP

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          git clone -b openssl-3.1.1 https://github.com/openssl/openssl.git
          cd openssl
          ./Configure mingw64 --cross-compile-prefix=x86_64-w64-mingw32- --prefix=<your install path>
          make -j build_sw
          make -j install_sw

      - name: Build FreeRDP
        run: |
          git clone https://github.com/FreeRDP/FreeRDP.git
          cd FreeRDP
          cmake -B build -S .
          cmake --build build --config Release

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: FreeRDP DLLs
          path: FreeRDP/build/bin/Release
