name: Build FreeRDP DLLs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSVC environment
        uses: microsoft/setup-msbuild@v1

      - name: Build FreeRDP
        run: |
          MSBuild /p:Configuration=Release /p:Platform=x64
          # Additional build commands if needed

      - name: Create artifact
        uses: actions/upload-artifact@v2
        with:
          name: FreeRDP DLLs
          path: FreeRDP/build/bin/Release
