name: Build FreeRDP DLLs

on:
  push:
    branches:
        - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout FreeRDP
      run: |
        git clone https://github.com/FreeRDP/FreeRDP.git

    - name: Checkout dependencies
      run: |
        cd FreeRDP
        git clone https://github.com/cisco/openh264.git

    - name: Build OpenSSL
      run: |
        cd openssl
        ./Configure mingw64 --cross-compile-prefix=x86_64-w64-mingw32- --prefix=<your install path>
        make -j build_sw
        make -j install_sw

    - name: Build FreeRDP
      run: |
        cd FreeRDP
        # Add necessary build commands and options for FreeRDP

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: freerdp-artifacts
        path: artifacts/

