name: Build FreeRDP for Windows x64

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSVC 2012
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install OpenSSL
        run: |
          curl -L -o openssl.exe https://slproweb.com/download/Win64OpenSSL-1_1_1L.exe
          Start-Process -Wait -NoNewWindow -FilePath openssl.exe -ArgumentList "/silent /sp- /suppressmsgboxes /DIR=C:\OpenSSL-Win64"
          Remove-Item openssl.exe
        shell: powershell

      - name: Install CMake
        run: |
          curl -L -o cmake.msi https://github.com/Kitware/CMake/releases/download/v3.21.3/cmake-3.21.3-windows-x86_64.msi
          Start-Process -Wait -NoNewWindow -FilePath msiexec.exe -ArgumentList "/i cmake.msi /quiet"
          Remove-Item cmake.msi
          $env:PATH = 'C:\cmake\cmake-3.21.2-win64-x64\bin;' + $env:PATH
        shell: powershell

      - name: Build FreeRDP
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 11 Win64"
          cmake --build . --config Release
        shell: powershell

      - name: Create Artifact
        run: |
          mkdir artifacts
          mv build/Release/*.dll artifacts/
        shell: powershell

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: FreeRDP-Windows-x64
          path: artifacts/
