name: Build FreeRDP DLLs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code pass
        uses: actions/checkout@v2

      - name: Set up MSVC 2012
        uses: actions/setup-msbuild@v1
        with:
          vs-version: 2012
          architecture: x64

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Install OpenSSL
        run: |
          curl -LO https://slproweb.com/download/Win64OpenSSL-1_1_1l.exe
          Start-Process -Wait -FilePath .\Win64OpenSSL-1_1_1l.exe -ArgumentList '/SP- /VERYSILENT /SUPPRESSMSGBOXES /DIR="C:\OpenSSL"'
          Remove-Item .\Win64OpenSSL-1_1_1l.exe

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build DLLs
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
            name: DLLs
            path: build
  